name: clinical_trials_env
channels:
  - conda-forge
dependencies:
  - python=3.11
  - python-dotenv
  - pytest
  - pandas
  - psycopg2
  - duckdb
  - jupyter
  - ipywidgets
  - pyarrow
  - matplotlib
  - rapidfuzz
  - anthropic
  - pip
